apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2c7fac87
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2c7fac87
  template:
    metadata:
      labels:
        app: app-2c7fac87
    spec:
      containers:
      - image: app-2c7fac87:latest
        name: app-2c7fac87
        ports:
        - containerPort: 8080
